<!DOCTYPE html>
<html>
<body>

<form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" method="post">
Test json string <input type="text" name="jsonstring"><br>
<input type="submit">
</form>
<br><h2>Result:</h2>

<?php
 include '../config.php'; 
	$jsonArray;
	$UserType;
	$CreatorUserID;
	$JobTitle;
	$IsGenericPhoto;
	$CategoriesTitleArray; //array
	$ScopesJsonArray; //array
	$MinAge;
	$MaxAge;
	$TotalPax;
	$ReqMinEduLevel;
	$Country;
	$State;
	$City;
	$Lng;
	$Lat;
	$StartDateTime;
	$EndDateTime;
	$IsSalaryDaily;
	$Payout;
	$PostBoosted;
 	$ScopesJsonStr;
 	$JobCategoriesStr;
 	$CurrentlyRecruited; //generated by system
 	$JobStatus; //generated by system
 	$TotalWorkDays; //generated by system
 	$JobID; //generate uniqueKey
 	
 $content = file_get_contents('php://input');	
 if($content){ 
 	/*Actual code for deployment*/
 	$jsonArray = json_decode($content, true);
 	
 	/*Debug code - $_POST can only be use for debugging */
 	//$jsonString = $_POST['jsonstring'];
 	//$jsonArray = json_decode($jsonString, true);
 	
 	$JobID= uniqid();
 	extractInfo($jsonArray);
 	insertToTable($con);
 }
 
 function extractInfo($jsonArray){
	global $UserType,$CreatorUserID,$JobTitle, $IsGenericPhoto,$CategoriesTitleArray,$ScopesJsonArray,$MinAge,$MaxAge,$TotalPax,$ReqMinEduLevel,$Country,$State,$City,$Lng,$Lat,$StartDateTime,$EndDateTime,$IsSalaryDaily,$Payout,$PostBoosted,$ScopesJsonStr,$JobCategoriesStr;	
 	$UserType = $jsonArray ['UserType'];
 	$CreatorUserID =  $jsonArray ['CreatorUserID'];
 	$JobTitle = $jsonArray ['JobTitle'];
 	$IsGenericPhoto = $jsonArray ['IsGenericPhoto'];
 	$CategoriesTitleArray = $jsonArray ['CategoriesTitle']; //array
 	$ScopesJsonArray = $jsonArray ['ScopesJson']; //array
 	$MinAge = $jsonArray ['MinAge'];
 	$MaxAge = $jsonArray ['MaxAge'];
 	$TotalPax = $jsonArray ['TotalPax'];
 	$ReqMinEduLevel = $jsonArray ['ReqMinEduLevel'];
 	$Country = $jsonArray ['Country'];
 	$State = $jsonArray ['State'];
 	$City = $jsonArray ['City'];
 	$Lng= $jsonArray ['Lng'];
 	$Lat= $jsonArray ['Lat'];
 	$StartDateTime= $jsonArray ['StartDateTime'];
 	$EndDateTime= $jsonArray ['EndDateTime'];
 	$IsSalaryDaily= $jsonArray ['IsSalaryDaily'];
 	$Payout= $jsonArray ['Payout'];
 	$PostBoosted= $jsonArray ['PostBoosted'];
 
 	//formatting date
 	$StartDateTime = str_replace('/', '-', $StartDateTime);
 	$EndDateTime = str_replace('/', '-', $EndDateTime );
 	$StartDateTime = gmdate("Y-m-d H:i" , strtotime($StartDateTime));
 	$EndDateTime = gmdate("Y-m-d H:i" , strtotime($EndDateTime));
 	
 	//convert ScopesJsonArray to String
	$arrLength = count($ScopesJsonArray);
	for($i=0; $i<$arrLength; $i++){
		if($i==$arrLength-1){
			$ScopesJsonStr .= $ScopesJsonArray[$i];
		}
		else{
			$ScopesJsonStr .= $ScopesJsonArray[$i].",";
		}		
	}

 	//convert $JobCategory to String
 	/*$arrLength = count($CategoriesTitleArray);
 	for($i=0; $i<$arrLength; $i++){
		$JobCategoriesStr .= ",".$CategoriesTitleArray[$i].",";	
	}*/	
 }
 
 function insertToTable($con){
	global $JobID,$JobTitle, $IsGenericPhoto,$CategoriesTitleArray,$ScopesJsonArray,$MinAge,$MaxAge,$TotalPax,$ReqMinEduLevel,$Country,$State,$City,$Lng,$Lat,$StartDateTime,$EndDateTime,$IsSalaryDaily,$Payout,$PostBoosted,$ScopesJsonStr,$JobCategoriesStr,$UniqueKey;
	//convert to UTC datetime
 	$datePosted = gmdate('Y-m-d H:i:s');
 	echo 'datePosted :'.$datePosted .'<br>';
 	
 	//calculate diff startdate enddate
 	$TotalWorkDays = abs((strtotime($EndDateTime) - strtotime($StartDateTime))/86400);

	//insert Jobs table
	$insertQuery = "INSERT INTO `Jobs`(`JobID`, `UserType`, `CreatorUserID`, `DatePosted`, `JobTitle`, `IsGenericPhoto`, `MinAge`,`MaxAge`, `TotalPax`,`ReqMinEduLevel`, `Country`, `State`, `City`, `Lat`, `Lng`, `StartDateTime`, `EndDateTime`, `TotalWorkDays`, `IsSalaryDaily`, `SalaryCurrencyCode`, `Payout`, `CurrentlyRecruited`, `JobStatus`, `PostBoosted`,`LastModify`) VALUES ('$JobID','$UserType','$CreatorUserID','$datePosted','$JobTitle','$IsGenericPhoto',$MinAge,$MaxAge,$TotalPax,$ReqMinEduLevel,'$Country','$State','$City','$Lat','$Lng','$StartDateTime','$EndDateTime',$TotalWorkDays,'$IsSalaryDaily','sgd',$Payout,0,0,'$PostBoosted','$datePosted')";
	
	$result = mysql_query($insertQuery , $con);
        if (!$result) {
        	echo "Eror at insert Jobs query";
        	removeRecord($con);
            	die('Invalid query insert job: ' . mysql_error());
        }
        
        //insert Scope database
        $insertQuery = "INSERT INTO `Scope`(`JobID`, `ScopesJson`) VALUES ('$JobID','$ScopesJsonStr')";
        $result = mysql_query($insertQuery , $con); 
        if (!$result) {
        	echo "Eror at insert Scopes query";
        	removeRecord($con);
            	die('Invalid query insert scope: ' . mysql_error());          
        }
        
        $arrLength = count($CategoriesTitleArray);
        for($i=0; $i<$arrLength; $i++){    
        	$insertQuery = "INSERT INTO `Job_Categories`(`JobID`, `CategoryID`) VALUES ('$JobID',".$CategoriesTitleArray[$i].")";
        	$result = mysql_query($insertQuery , $con); 
        	if (!$result) {
        		echo "Eror at insert Job_Categories query";
        		removeRecord($con);
            		die('Invalid query insert categogry: ' . mysql_error());          
        	}
        }
 }
 
 function removeRecord($con){
 //Error in insert record, remove propagated insert
 	global $JobID;
 	echo "Record removed invalid insert: ".$JobID."<br>";
 	$DeleteFromJobQuery = "DELETE FROM `Jobs` WHERE `JobID` = \"".$JobID."\"";
 	$DeleteFromScope = "DELETE FROM `Scope` WHERE `JobID` = \"".$JobID."\"";
 	$DeleteFromJobCategory = "DELETE FROM `Job_Categories` WHERE `JobID` = \"".$JobID."\"";
 	$result = mysql_query($DeleteFromJobQuery, $con);
 	if (!$result) {
            die('Invalid query delete Job: ' . mysql_error());
        }
 	$result = mysql_query($DeleteFromScope, $con);
 	if (!$result) {
            die('Invalid query delete scope: ' . mysql_error());
        }
        $result = mysql_query($$DeleteFromJobCategory, $con);
 	if (!$result) {
            die('Invalid query delete JobCategory: ' . mysql_error());
        }
 }
 
 include '../close.php';
?>
</body>
</html>